name: Build and push with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ğŸ” Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ·ï¸ Extract Git commit SHA
        id: vars
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: ğŸ—ï¸ Build Docker images with docker-compose
        run: |
          docker compose -f docker-compose.yml build
          docker tag astousmk/laravel_image:latest astou/laravel_image:${{ env.SHA_SHORT }}

      - name: ğŸš€ Push images to Docker Hub
          run: |
          docker push astousmk/laravel_image:latest
          docker push astou/laravel_image:${{ env.SHA_SHORT }}
